name: nectara
description: App Description
ignoreFiles: .git node_modules vendor
modules:
  - name: template
    language: docker
    description: Module description
    volumes:
      - alias: "volume"
      - mountPath: "/var/www/"
    ports:
      - alias: "http"
        portNumber: 80
    functions:
      - name: entry
        description: the entry point for the function
